language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#  - bower install
#services: mongodb
after_success:
  - eval "$(ssh-agent -s)"
  - ssh-add $DEPLOY_KEY
  - git remote add deploy pi@hermesiot.ddns.net:/home/pi/repo/pro-hermes
  - git push deploy