language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
#  - bower install
#services: mongodb
after_success:
  - mkdir .travis
  - openssl aes-256-cbc -K $encrypted_c60eefdee1b2_key -iv $encrypted_c60eefdee1b2_iv -in id_rsa.pub.enc -out deploy-key -d
  - chmod 600 deploy-key # this key should have push access
  - cp deploy-key ~/.ssh/id_rsa
  - rm -rf _deploy
  - mkdir _deploy
  - cd _deploy
  - git remote add deploy pi@hermesiot.ddns.net:/home/pi/repo/pro-hermes
  - git push deploy master