language: node_js
node_js:
  - '0.10'
  - '0.11'
before_script:
  - npm install -g bower grunt-cli
#  - bower install
#services: mongodb
after_success:
  - cat $DEPLOY_KEY > .travis/deploy_key.pem
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy pi@hermesiot.ddns.net:/home/pi/repo/pro-hermes
  - git push deploy